import type {
  FeedbackBuildMessage,
  FeedbackComment,
  FeedbackIdea,
  FeedbackUpdate,
} from "./types";

const now = Date.now();
const days = (n: number) => new Date(now - n * 86_400_000).toISOString();

export const SEED_IDEAS: FeedbackIdea[] = [
  {
    id: "idea-collaborative-routes",
    slug: "collaborative-routes",
    userId: "team-explore",
    authorName: "Explore",
    title: "Collaborative routes",
    description:
      "Create a route with your friends and decide together where to go — without making route creation complicated.",
    category: "routes",
    status: "building",
    boostCount: 145,
    commentCount: 12,
    teamResponse:
      "We really like this. We're experimenting with how collaborative routes could work without making route creation complicated.",
    isVisible: true,
    isFeatured: true,
    isTeamCreated: true,
    duplicateOf: null,
    createdAt: days(28),
    updatedAt: days(2),
  },
  {
    id: "idea-smart-itineraries",
    slug: "smart-itinerary-suggestions",
    userId: "demo-user",
    authorName: "You",
    title: "Smart itinerary suggestions",
    description:
      "When I'm visiting a city for a weekend, suggest a day-by-day flow of places and routes based on what I already saved.",
    category: "ai",
    status: "planned",
    boostCount: 98,
    commentCount: 7,
    teamResponse:
      "This is on our planned list. We're defining how suggestions stay useful without feeling pushy.",
    isVisible: true,
    isFeatured: true,
    isTeamCreated: false,
    duplicateOf: null,
    createdAt: days(21),
    updatedAt: days(5),
  },
  {
    id: "idea-hidden-gems",
    slug: "hidden-gems-nearby",
    userId: "user-leo",
    authorName: "Leo",
    title: "Hidden gems nearby",
    description:
      "Surface lesser-known places near me that locals love — not only the most popular spots on the map.",
    category: "discover",
    status: "listening",
    boostCount: 76,
    commentCount: 9,
    teamResponse: null,
    isVisible: true,
    isFeatured: false,
    isTeamCreated: false,
    duplicateOf: null,
    createdAt: days(6),
    updatedAt: days(6),
  },
  {
    id: "idea-recommendation-control",
    slug: "more-control-over-recommendations",
    userId: "user-sofia",
    authorName: "Sofía",
    title: "More control over recommendations",
    description:
      "Let me tune what Explore shows me — quieter places, food-first, outdoors, or family-friendly — without resetting my whole feed.",
    category: "discover",
    status: "considering",
    boostCount: 64,
    commentCount: 4,
    teamResponse:
      "We're reviewing how preference controls can stay simple while still feeling powerful.",
    isVisible: true,
    isFeatured: false,
    isTeamCreated: false,
    duplicateOf: null,
    createdAt: days(12),
    updatedAt: days(4),
  },
  {
    id: "idea-community-routes",
    slug: "community-route-discovery",
    userId: "user-andre",
    authorName: "André",
    title: "Community route discovery",
    description:
      "Make it easier to find great routes from creators and travelers in a city, with clearer signals for quality and freshness.",
    category: "community",
    status: "listening",
    boostCount: 51,
    commentCount: 5,
    teamResponse: null,
    isVisible: true,
    isFeatured: false,
    isTeamCreated: false,
    duplicateOf: null,
    createdAt: days(3),
    updatedAt: days(3),
  },
  {
    id: "idea-save-routes",
    slug: "save-entire-routes",
    userId: "user-nina",
    authorName: "Nina",
    title: "Save entire routes",
    description: "Let me bookmark a full route in one tap and reopen it later with all stops intact.",
    category: "routes",
    status: "shipped",
    boostCount: 212,
    commentCount: 18,
    teamResponse: "Shipped. You can save entire routes and find them quickly from your profile.",
    isVisible: true,
    isFeatured: true,
    isTeamCreated: false,
    duplicateOf: null,
    createdAt: days(60),
    updatedAt: days(10),
  },
  {
    id: "idea-place-hours",
    slug: "clearer-place-hours",
    userId: "user-cara",
    authorName: "Cara",
    title: "Clearer place hours",
    description:
      "Show opening hours more clearly on place pages, especially when I'm planning evening plans.",
    category: "places",
    status: "shipped",
    boostCount: 88,
    commentCount: 6,
    teamResponse: "Shipped with improved hours display on place details.",
    isVisible: true,
    isFeatured: true,
    isTeamCreated: false,
    duplicateOf: null,
    createdAt: days(55),
    updatedAt: days(14),
  },
  {
    id: "idea-events-nearby",
    slug: "local-events-nearby",
    userId: "user-jamal",
    authorName: "Jamal",
    title: "Local events nearby",
    description:
      "Surface happenings around me this week that fit the places and vibes I already explore.",
    category: "events",
    status: "planned",
    boostCount: 43,
    commentCount: 3,
    teamResponse: null,
    isVisible: true,
    isFeatured: false,
    isTeamCreated: false,
    duplicateOf: null,
    createdAt: days(9),
    updatedAt: days(8),
  },
];

export const SEED_COMMENTS: FeedbackComment[] = [
  {
    id: "c1",
    ideaId: "idea-collaborative-routes",
    userId: "user-maya",
    authorName: "Maya",
    body: "Would love invite links that expire after the trip weekend.",
    isVisible: true,
    createdAt: days(4),
    updatedAt: days(4),
  },
  {
    id: "c2",
    ideaId: "idea-collaborative-routes",
    userId: "user-leo",
    authorName: "Leo",
    body: "Voting on stops together would be perfect for group trips.",
    isVisible: true,
    createdAt: days(3),
    updatedAt: days(3),
  },
];

export const SEED_UPDATES: FeedbackUpdate[] = [
  {
    id: "u1",
    ideaId: "idea-collaborative-routes",
    status: "building",
    body: "Moved into building. Prototyping shared editing without clutter.",
    createdAt: days(2),
  },
  {
    id: "u2",
    ideaId: "idea-smart-itineraries",
    status: "planned",
    body: "Starred and moved to planned. Let's build this with you.",
    createdAt: days(5),
  },
];

export const SEED_BUILD_MESSAGES: FeedbackBuildMessage[] = [
  {
    id: "bm1",
    ideaId: "idea-smart-itineraries",
    userId: "team-explore",
    authorName: "Explore Team",
    body: "We starred your idea. Want to help shape how weekend itineraries feel in Explore?",
    isTeam: true,
    createdAt: days(4),
  },
  {
    id: "bm2",
    ideaId: "idea-smart-itineraries",
    userId: "demo-user",
    authorName: "You",
    body: "Yes — I'd love a simple 2-day plan based on places I already saved, not a huge AI dump.",
    isTeam: false,
    createdAt: days(3),
  },
];
