-- Administrative audit support for controlled production seed batches.
-- This migration creates no seed data and is never invoked automatically.

CREATE TABLE public.production_seed_batches (
  batch_id          TEXT PRIMARY KEY,
  target_project_ref TEXT NOT NULL CHECK (target_project_ref ~ '^[a-z0-9]{20}$'),
  status            TEXT NOT NULL DEFAULT 'running'
    CHECK (status IN ('running', 'completed', 'failed', 'rolling_back', 'rolled_back')),
  configuration     JSONB NOT NULL DEFAULT '{}'::jsonb,
  report            JSONB,
  started_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at       TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT production_seed_batch_id_format CHECK (
    batch_id ~ '^explore-production-seed-[a-z0-9][a-z0-9-]{2,50}$'
  )
);

CREATE TABLE public.production_seed_entries (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id       TEXT NOT NULL REFERENCES public.production_seed_batches(batch_id),
  entity_type    TEXT NOT NULL CHECK (entity_type IN (
    'auth_user', 'user', 'place', 'place_photo', 'existing_place_photo',
    'route', 'gps_segment', 'route_place', 'review', 'route_rating',
    'favorite', 'follower', 'storage_object'
  )),
  entity_id      TEXT NOT NULL CHECK (btrim(entity_id) <> ''),
  action         TEXT NOT NULL CHECK (action IN ('created', 'modified')),
  storage_bucket TEXT,
  storage_path   TEXT,
  before_data    JSONB,
  metadata       JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT production_seed_storage_pair CHECK (
    (storage_bucket IS NULL AND storage_path IS NULL)
    OR (storage_bucket IS NOT NULL AND storage_path IS NOT NULL)
  )
);

CREATE UNIQUE INDEX production_seed_entries_created_entity_unique
  ON public.production_seed_entries(batch_id, entity_type, entity_id, action);

CREATE INDEX production_seed_entries_batch_created_at
  ON public.production_seed_entries(batch_id, created_at DESC);

ALTER TABLE public.production_seed_batches ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.production_seed_entries ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.production_seed_batches FROM PUBLIC, anon, authenticated;

REVOKE ALL ON public.production_seed_entries FROM PUBLIC, anon, authenticated;

REVOKE ALL ON SEQUENCE public.production_seed_entries_id_seq FROM PUBLIC, anon, authenticated;

GRANT SELECT, INSERT, UPDATE ON public.production_seed_batches TO service_role;

GRANT SELECT, INSERT ON public.production_seed_entries TO service_role;

GRANT USAGE, SELECT ON SEQUENCE public.production_seed_entries_id_seq TO service_role;

-- Returns the exact place/photo fields needed by dry-run duplicate and image
-- auditing. Keeping geography extraction server-side avoids assuming how
-- PostgREST serializes PostGIS values.
CREATE OR REPLACE FUNCTION public.production_seed_place_inventory()
RETURNS TABLE (
  id UUID,
  name TEXT,
  description TEXT,
  category TEXT,
  state TEXT,
  moderation_status TEXT,
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  created_by UUID,
  photos JSONB
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    p.id,
    p.name,
    p.description,
    p.category::text,
    p.state::text,
    p.moderation_status,
    ST_Y(p.location::geometry) AS lat,
    ST_X(p.location::geometry) AS lng,
    p.created_by,
    COALESCE(
      jsonb_agg(
        jsonb_build_object(
          'id', pp.id,
          'url', pp.url,
          'position', pp.position
        ) ORDER BY pp.position, pp.created_at
      ) FILTER (WHERE pp.id IS NOT NULL),
      '[]'::jsonb
    ) AS photos
  FROM public.places p
  LEFT JOIN public.place_photos pp ON pp.place_id = p.id
  GROUP BY p.id;
$$;

REVOKE ALL ON FUNCTION public.production_seed_place_inventory() FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.production_seed_place_inventory() TO service_role;
